<footer>
    <ul>    
        <li><a href="https://www.linkedin.com/in/timothy-m-johnson" class="plain-link"><i class="fab fa-linkedin"></i></a></li>
        <li><a href="https://www.facebook.com/itstimjohnson" class="plain-link"><i class="fab fa-facebook-square"></i></a></li>
        <li><a href="https://twitter.com/itsmetimjohnson" class="plain-link"><i class="fab fa-twitter-square"></i></a></li>
    </ul>
</footer>
