<?php
    $uri = explode('?', $_SERVER['REQUEST_URI'], 2)[0];
    $links = [
        '/'         => 'About',
        '/blog'     => 'Blog',
        '/projects' => 'Projects',
        '/contact'  => 'Contact&nbsp;Me',
    ];
?>

<header>
    <a id="title" href="/">hey,&nbsp;it's&nbsp;Tim&nbsp;Johnson</a>
    <nav>
        <ul>
            <?php foreach ($links as $path => $name): ?>
            <li>
                <a href="<?= $path ?>" class="plain-link<?php if ($uri === $path) echo ' current' ?>">
                    <?php echo $name ?>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </nav>
</header>
