<!DOCTYPE html>
<html lang="en-us">

<?= $head ?>

<body>
    <?= $header ?>
    <div id="content-container">
        <div id="content-column">
            <div id="header-spacer"></div>
            <main>
                <h1><?= $title ?></h1>
                <?= $page ?>
            </main>
        </div>
        <?= $footer ?>   
    </div>
    
</body>

<?php if (isset($jsonData)): ?>
    <?php foreach ($jsonData as $rowName => $rowData): ?>
        <script id="<?= $rowName ?>" type="application/json"><?= $rowData ?></script>
    <?php endforeach ?>
<?php endif ?>

</html>
