<!DOCTYPE html>
<html lang="en-us">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Slider</title>
	<link rel="shortcut icon" href="/assets/images/favicon.ico">
	<link rel="stylesheet" type="text/css" href="/assets/css/slider.css">
	<script type="text/javascript" src="/assets/js/slider.js"></script>
</head>
<body>
	<h1>Slider</h1>
	<div id="game">
		<div id="game_container"></div>
		<div id="info">
			<div id="level_title"></div>
			<div id="level_number"></div>
			<div id="timer"></div>
			<h2>Controls</h2>
			<ul>
				<li><b>Arrow Keys/WASD:</b> Move the player up, down, left, or right.</li>
				<li><b>R:</b> Restart the level, or if the game is over, the game</li>
				<li><b>Space:</b> Pause/Unpause game, freezing your time</li>
			</ul>
			<h2 class="about">About</h2>
			<p class="about">
				Slider is a game that I, Tim Johnson, originally created for my senior project in high school. 
				My objective was simply to make a game, and that's exactly what I did! After a few forays into
				C++ attempting to make a more complex game, I eventually settled into something that I could
				reasonably accomplish. The original game was created using Python 2.12 and a library called
				PyGame, making it a little harder to just start up and play. This is why I chose to port the 
				game here using Javascript. Now, if I want to show anyone my work, I just direct them here!
				Enjoy these twelve levels of puzzle solving fun!
			</p>
		</div>
	</div>
</body>
</html>
