<div id='page-content'>
    <div id="form-container">
        <h2>Send a Message</h2>
        <form>
            <label for="form-name">Name</label>
            <input id="form-name" name="name">
            <label for="form-email">Email</label>
            <input id="form-email" name="email">
            <label for="form-message">Message</label>
            <textarea id="form-message" name="message" rows=25 style="resize: none"></textarea>
        </form>
    </div>
    <div id="contact-info">
        <h2>Contact Info</h2>
        <b>Email:</b><a href="mailto: tim@itstimjohnson.com" class="plain-link"> tim@itstimjohnson.com</a>
    </div>
</div>
