<div class="project">
    <h2>Slider Game</h2>
    <div class="links">
        <a href="/projects/slider" target="_blank">Check It Out!</a>
        <a href="https://github.com/thecreatorguy/slider-game">Github <i class="fab fa-github-square"></i></a>
    </div>
    <img src="/assets/images/slider-pic.png" height="300px" width="300px"/>
    <p>
        Slider is a game that I originally created for my senior project in high school. My only objective was to
        make a game, any game. And that's exactly what I did! After a short foray into C++, I decided that I should
        probably choose something more achievable for my skill level. I made a small game using a grid and a character
        that moves in straight lines, sliding until reaching a solid object, and passing between and over obstacles
        like lava, switches, and teleporters to make the puzzle game a little challenging. The original game was
        created in Python 2.12 and with a graphics library called PyGame. Unfortunately, this made the game difficult
        to show to my friends and family. For this reason I chose to port the game to the web using Javascript.
    </p>
    <p>
        During freshman year of college, I learned about graphs and breadth-first search in CS2. I thought that
        would be perfect to apply to my old project for finding the shortest solution to each of my hand-crafted
        levels. It actually found a shorter solution for my 11th level!
    </p>
</div>
<div class="project">
    <h2>Website</h2>
    <div class="links">
        <a href="https://github.com/thecreatorguy/website">Github <i class="fab fa-github-square"></i></a>
    </div>
    <p>
        I made this website using <a href="https://codeigniter.com/">CodeIgniter</a> entirely by myself! I originally 
        purchased the domain and hosting mostly as a place to put my email and projects (only the slider game so far), 
        but I've decided that it should probably look decent now that I have more experience with web technologies.
        In addition, I wanted to have a space to write down my interesting and cool thoughts!
    </p>
</div>
