<div id="slider-game">
    <div id="game-container"></div>
    <div id="info">
    	<h3>Controls</h3>
    	<dl>
    		<dt>Arrow Keys/WASD:</dt><dd> Move the player up, down, left, or right</dd>
    		<dt>R:</dt><dd>Restart the level. If the game is over, restarts the game</dd>
    		<dt>Space:</dt><dd>Pause/Unpause game, freezing your time</dd>
    	</dl>
    </div>
</div>
<div id="alt-content">
    <p>Sorry, but the Slider Game can only be played on a desktop.</p>
</div>
